"""CLI inference for SMS spam detection.

Usage:
  python predict.py --text "win a free prize now"

Requires artifacts generated by running sms-spam-detection.ipynb:
  - artifacts/sms_spam_calibrated.joblib
  - artifacts/metadata.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import joblib
import pandas as pd


def load_metadata(metadata_path: Path) -> dict:
    if not metadata_path.exists():
        raise FileNotFoundError(f"Missing metadata: {metadata_path}")
    with metadata_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_model(model_path: Path):
    if not model_path.exists():
        raise FileNotFoundError(f"Missing model artifact: {model_path}")
    return joblib.load(model_path)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="predict.py",
        description="Predict spam probability for an SMS message.",
    )
    p.add_argument("text", nargs="?", help="Message text (optional if --text is provided).")
    p.add_argument("--text", dest="text_flag", help="Message text.")
    p.add_argument("--artifacts-dir", default="artifacts", help="Artifacts directory.")
    p.add_argument("--model", default="sms_spam_calibrated.joblib", help="Model file name inside artifacts dir.")
    p.add_argument("--metadata", default="metadata.json", help="Metadata file name inside artifacts dir.")
    p.add_argument(
        "--threshold",
        type=float,
        default=None,
        help="Decision threshold override. Default: metadata opt_threshold or 0.5.",
    )
    p.add_argument("--json", action="store_true", help="Print output as JSON.")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    text = args.text_flag if args.text_flag is not None else args.text
    if not text:
        print("Error: Provide a message via positional arg or --text.", file=sys.stderr)
        return 2

    artifacts_dir = Path(args.artifacts_dir)
    model_path = artifacts_dir / args.model
    meta_path = artifacts_dir / args.metadata

    try:
        meta = load_metadata(meta_path)
    except FileNotFoundError:
        meta = {}

    try:
        model = load_model(model_path)
    except FileNotFoundError as e:
        print(str(e), file=sys.stderr)
        print("Run sms-spam-detection.ipynb to generate artifacts.", file=sys.stderr)
        return 2

    threshold = args.threshold
    if threshold is None:
        try:
            threshold = float(meta.get("opt_threshold", 0.5))
        except Exception:
            threshold = 0.5

    df = pd.DataFrame({"text": [text]})
    proba = float(model.predict_proba(df)[:, 1][0])
    pred = int(proba >= float(threshold))

    label = "spam" if pred == 1 else "ham"
    label_map = meta.get("label_map")
    if isinstance(label_map, dict):
        inv = {}
        for k, v in label_map.items():
            try:
                inv[int(v)] = str(k)
            except Exception:
                pass
        label = inv.get(pred, label)
    out = {
        "text": text,
        "spam_probability": proba,
        "threshold": float(threshold),
        "prediction": pred,
        "prediction_label": label,
        "model_path": str(model_path),
    }

    if args.json:
        print(json.dumps(out, ensure_ascii=False))
    else:
        print(f"spam_probability: {proba:.4f}")
        print(f"threshold:        {float(threshold):.4f}")
        print(f"prediction:       {pred} ({label})")
        print(f"model:            {model_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
